name: Bug Report
description: When a feature is not behaving as expected.
type: Bug

body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to replicate the issue. Provide specific details or links to demonstrate the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: LumoraVR Version
      placeholder: e.g., 1.2.3
    validations:
      required: true
  - type: dropdown
    id: application-type
    attributes:
      label: Application Type
      description: Select the context this bug appears on.
      options:
        - "Main Application"
        - "Debug Window"
        - "Other"
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "Android / Quest"
    validations:
      required: true
  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: Attach logs replicating the issue.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any extra details relevant to the issue.
    validations:
      required: false
  - type: textarea
    id: reporters
    attributes:
      label: Reporter Credits
      description: List usernames of anyone who discovered the bug (including yourself) for credit in release notes.
