name: .NET Build Validation
on:
  pull_request:
    branches: 
      - main
jobs:
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Aquamarine.csproj
      continue-on-error: true
    
    - name: Build project
      id: build
      run: dotnet build Aquamarine.csproj --no-restore --configuration ExportRelease
      continue-on-error: true
    
    - name: Add build-error label if build fails
      if: steps.build.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['build-error']
          })
    
    - name: Fail if build errors found
      if: steps.build.outcome == 'failure'
      run: |
        echo "::error::Build failed for Aquamarine.csproj. Please fix the build errors before merging."
        exit 1
