name: 'Check for merge conflicts'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "Has Conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}